@startuml

actor "Клиника" as Clinic
actor "Аналитик" as Analyst

rectangle "Medical Domain" {
  [Medical Systems]
}

rectangle "Fintech Domain" {
  [Fintech Services]
}

rectangle "AI Domain" {
  [AI Services]
}

rectangle "Corporate Domain" {
  [Corporate Systems]
}

rectangle "Streaming Platform (Kafka)" {
  [Event Bus]
}

rectangle "Data Platform" {
  [Data Lake]
  [Lakehouse]
  [Data Products]
}

rectangle "BI / Data Portal" {
  [BI]
  [Data Portal]
}

[Medical Systems] --> [Event Bus] : события (визиты, загрузка)
[Fintech Services] --> [Event Bus] : транзакции
[AI Services] --> [Event Bus] : результаты моделей
[Corporate Systems] --> [Event Bus]

[Pharma Systems] --> [Event Bus]
[Device Systems] --> [Event Bus]

[Event Bus] --> [Data Lake]

[Data Lake] --> [Lakehouse]
[Lakehouse] --> [Data Products]

[Data Products] --> [BI]
[Data Products] --> [Data Portal]

[Medical Systems] --> [AI Services] : данные (через API)
[AI Services] --> [Medical Systems] : прогнозы

[Medical Systems] --> [Fintech Services] : запрос оплаты
[Fintech Services] --> [Medical Systems] : статус

@enduml